### ISSUE TITLE
Odd message:  Error: Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by johnholt** [hpcc-systems/vscode-ecl#95] opened 2018-05-07 19:23 UTC
The location says line 120 col 43

Version says 0.0.28

**Comment by GordonSmith** [comment] 2018-05-08 07:44
@johnholt can you send me your launch config and any custom settings you might have set?  (Can you reproduce it?)

**Comment by johnholt** [comment] 2018-05-08 11:37
It has occurred several times.  I changed the extensions to txt so I could attach.
[code-workspace.txt](https://github.com/hpcc-systems/vscode-ecl/files/1983698/code-workspace.txt)
[launch.txt](https://github.com/hpcc-systems/vscode-ecl/files/1983699/launch.txt)
[settings.txt](https://github.com/hpcc-systems/vscode-ecl/files/1983700/settings.txt)

**Comment by johnholt** [comment] 2018-05-08 11:43
It has occurred several times.  I changed the extensions to txt to upload.
[code-workspace.txt](https://github.com/hpcc-systems/vscode-ecl/files/1983716/code-workspace.txt)
[launch.txt](https://github.com/hpcc-systems/vscode-ecl/files/1983717/launch.txt)
[settings.txt](https://github.com/hpcc-systems/vscode-ecl/files/1983718/settings.txt)

**Comment by GordonSmith** [comment] 2018-05-10 10:14
@johnholt where are you seeing that message (Debug Console?).
Also are you performing any specific action at the time (like a syntax check or submit)?

Can you check the "OUTPUT" view for more information (you may need to select ECL from the drop combo.

Also if you email me a screenshot that may help a lot...

**Comment by johnholt** [comment] 2018-05-10 11:47
It is showing up in something similar to Notifications in OS X, but at the bottom right of the application frame.  I'll snap a screen shot.  I'll be working on that project again later today or tomorrow.

**Comment by johnholt** [comment] 2018-05-11 12:11
[Illegal_Arg_Error.pdf](https://github.com/hpcc-systems/vscode-ecl/files/1995224/Illegal_Arg_Error.pdf)

An example is attached.  It is important to note that module in the edit window uses FORWARD, so the error may be how you are using eclcc.  When FORWARD is removed, the error stops appearing.

**Comment by GordonSmith** [comment] 2018-05-31 10:19
This is duplicate of:  https://github.com/hpcc-systems/vscode-ecl/issues/109 (which has a full stack trace)

**Closed by GordonSmith** 2018-05-31 10:19 UTC
Labels: duplicate
